/* Product data for the standalone piece pages (piece.html?id=<slug>) and the
 * Buy/price line on the gallery tiles. Keep in sync with gallery.html /
 * index.html tile markup — this is the single source of truth for price,
 * availability, and the buy link; the gallery tiles are also updated by hand
 * to show the price under each title.
 *
 * buyUrl: '' until real per-item Square checkout links are wired in. Empty
 * means the piece page shows an "Inquire" button to the contact form instead
 * of a broken/fake payment link.
 * price / available: null means pricing isn't confirmed yet — the page shows
 * "Price on request" rather than guessing a number.
 */
const PIECES = [
  {
    id: 'reflection',
    title: 'Reflection',
    category: 'Wildlife',
    medium: 'Patinated Bronze',
    edition: 'Limited Edition',
    price: 3500,
    available: 2,
    buyUrl: 'https://square.link/u/sOQNF61Q',
    image: 'Photos/web/LionDrinking.jpg',
    description: 'A lion caught mid-thought, the patina laid in warm layers so the light moves with it.',
  },
  {
    id: 'chief-in-waiting',
    title: 'Chief in Waiting',
    category: 'Native Heritage',
    medium: 'Bronze',
    edition: 'Limited Edition',
    price: 7100,
    available: 1,
    buyUrl: 'https://square.link/u/E9babN3K',
    image: 'Photos/web/Indian.jpg',
    description: 'A quiet study of Native heritage, cast in bronze and finished entirely by hand.',
  },
  {
    id: 'on-the-prowl',
    title: 'On the Prowl',
    category: 'Wildlife',
    medium: 'Patinated Bronze',
    edition: 'Limited Edition',
    price: 4200,
    available: 3,
    buyUrl: 'https://square.link/u/Qgu34g7a',
    image: 'Photos/web/MountainLion.jpg',
    description: 'A cougar in motion, muscle and tension captured mid-stride through the lost-wax process.',
  },
  {
    id: 'i-see-you',
    title: 'I See You',
    category: 'Wildlife',
    medium: 'Patinated Bronze',
    edition: 'Limited Edition',
    price: 4200,
    available: 3,
    buyUrl: 'https://square.link/u/6oWkneMu',
    image: 'Photos/web/ProngHorn.jpg',
    description: "A pronghorn's stare, rendered in a rich patinated finish — alert, watchful, unmistakably western.",
  },
  {
    id: 'the-bear',
    title: 'The Bear',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: 3400,
    available: 3,
    buyUrl: 'https://square.link/u/4VOMlQ8G',
    image: 'Photos/web/BearCoatRack.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'the-bison',
    title: 'The Bison',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: 3400,
    available: 3,
    buyUrl: 'https://square.link/u/uVNrO8Zj',
    image: 'Photos/web/BisonCoatRack.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'mine-boss',
    title: 'Mine Boss',
    category: 'Western',
    medium: 'Bronze',
    edition: 'Historical Series',
    price: 3600,
    available: 1,
    buyUrl: 'https://square.link/u/H4K3O3Cl',
    image: 'Photos/web/MineBoss.jpg',
    description: "A seated coal miner on his break, marked with the SUFCo #1 seam — a tribute to Utah's mining history.",
  },
  {
    id: 'the-wolf',
    title: 'The Wolf',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: 3400,
    available: 3,
    buyUrl: 'https://square.link/u/qZTQPcbN',
    image: 'Photos/web/WolfCoatRack.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'the-moose',
    title: 'The Moose',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: 3400,
    available: 4,
    buyUrl: 'https://square.link/u/27rjv9DZ',
    image: 'Photos/web/MooseCoatRack.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'coming-to-town',
    title: 'Coming to Town',
    category: 'Western',
    medium: 'Painted Bronze',
    edition: 'Holiday Series',
    price: 5500,
    available: 1,
    buyUrl: 'https://square.link/u/AfhndwMP',
    image: 'Photos/web/Santa.jpg',
    description: 'A western Santa bringing warmth and story to the piece, hand-painted in bronze.',
  },
  {
    id: 'the-elk',
    title: 'The Pronghorn',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: null,
    available: null,
    buyUrl: '',
    image: 'Photos/web/DSC_5958.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'the-ram',
    title: 'The Ram',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: 'Functional Art',
    price: 3400,
    available: 3,
    buyUrl: 'https://square.link/u/wcHwnSNp',
    image: 'Photos/web/IMG_1643.jpg',
    description: 'A working coat rack cast in the same bronze and detail as the gallery pieces.',
  },
  {
    id: 'pronghorn-skull',
    title: 'Pronghorn Skull',
    category: 'Coat Rack',
    medium: 'Bronze Coat Rack',
    edition: '',
    price: 2500,
    available: 2,
    buyUrl: 'https://square.link/u/DLvVNKuA',
    image: 'Photos/web/IMG_1635.jpg',
    description: 'A pronghorn skull wall piece, cast in bronze with the same hand-finished detail as the rest of the collection.',
  },
  {
    id: 'bison-skull',
    title: 'Bison Skull',
    category: 'Coat Rack',
    medium: 'Bronze Wall Sculpture',
    edition: '',
    price: 2500,
    available: 2,
    buyUrl: 'https://square.link/u/oGPkhMHF',
    image: 'Photos/web/DSC_5857.jpg',
    description: 'A bison skull wall piece, cast in bronze with the same hand-finished detail as the rest of the collection.',
  },
];

function getPiece(id) {
  return PIECES.find((p) => p.id === id) || null;
}

function formatPrice(price) {
  if (price == null) return 'Price on request';
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(price);
}
